#!/bin/bash

echo "Generating databases with different table counts..."

# Create databases with 1,000, 5,000, and 10,000 tables
python3 gen-database.py database_10.db -t 10
python3 gen-database.py database_1k.db -t 1000
python3 gen-database.py database_5k.db -t 5000  
python3 gen-database.py database_10k.db -t 10000

echo "Database generation complete."
