// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.10.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'value.dart';
part 'params.freezed.dart';

@freezed
sealed class Params with _$Params {
  const Params._();

  const factory Params.none() = Params_None;
  const factory Params.positional(List<Value> field0) = Params_Positional;
  const factory Params.named(List<(String, Value)> field0) = Params_Named;
}
