// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.10.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'value.freezed.dart';

@freezed
sealed class Value with _$Value {
  const Value._();

  const factory Value.integer(PlatformInt64 field0) = Value_Integer;
  const factory Value.real(double field0) = Value_Real;
  const factory Value.text(String field0) = Value_Text;
  const factory Value.blob(Uint8List field0) = Value_Blob;
  const factory Value.null_() = Value_Null;
}
