// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.10.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../helpers/params.dart';
import '../helpers/result.dart';
import '../helpers/return_value.dart';
import '../helpers/value.dart';
import '../helpers/wrapper.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `run`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RustStatement>>
abstract class RustStatement implements RustOpaqueInterface {
  Future<ExecuteResult> execute({required Params params});

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<RustStatement> newInstance({
    required WrapperStatement statement,
    required WrapperArcConnection connection,
  }) => RustLib.instance.api.crateApiStatementRustStatementNew(
    statement: statement,
    connection: connection,
  );

  Future<QueryResult> query({required Params params});

  Future<void> reset();
}
