#!/bin/bash

# if RUST_LOG is non-empty, enable tracing output
if [ -n "$RUST_LOG" ]; then
   target/debug/limbo --experimental-indexes -m list -t testing/test.log "$@"
else
   target/debug/limbo --experimental-indexes -m list "$@"
fi
