#!/bin/bash

set -e

if [[ -n "$@" ]]; then
    TURSO_ENABLE_CHECKPOINT_CACHE=1 cargo run -p limbo_sim -- "$@"
else
    echo "Running limbo_sim in infinite loop..."
    while true; do
        TURSO_ENABLE_CHECKPOINT_CACHE=1 cargo run -p limbo_sim
    done
fi
