/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class Database {
  memory: boolean
  constructor(path: string)
  prepare(sql: string): Statement
}
export declare class Statement {
  get(): NapiResult
}
