name: Stale

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC

permissions:
  issues: read
  pull-requests: write

jobs:
  stale:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
      - name: Close stale pull requests
        uses: actions/stale@v6
        with:
          repo-token: ${{ secrets.GH_TOKEN }}
          operations-per-run: 1000
          ascending: true
          stale-pr-message: 'This pull request has been marked as stale due to inactivity. It will be closed in 7 days if no further activity occurs.'
          close-pr-message: 'This pull request has been closed due to inactivity. Please feel free to reopen it if you have further updates.'
          days-before-issue-stale: 365
          days-before-stale: 30
          days-before-close: 7
